site_name: Safe You V1.0
theme:
  palette:
    primary: blue
  name: material
  font:
    text: Roboto
  language: en
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Tiếng Việt
      link: /vi/
      lang: vi
