site_name: Safe You
theme:
  palette:
    primary: blue
  name: material
  logo: assets/images/logo.png
  font:
    text: Raleway
  language: en
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Tiếng Việt
      link: /vi/
      lang: vi
